### ISSUE TITLE
drag and drop files issue https://share.descript.com/view/yPGk95hmgZA

### ISSUE THREAD

**Issue by aliscie** [aliscie/autodox-tauri#19]

**Comment by aliscie** [comment]
remove `height: 0;` and ` height: 20px;`
```css

.nested {
    opacity: 0;
    display: none;
    transition: 0.3s;
}

.active {
    display: block;
    opacity: 1;
    transition: 0.3s;
}
```
